Models/OSSB_IMAGEM.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSSB_IMAGEM
    {
        public int ID { get; set; }
        public string DESCRICAO { get; set; }
        public int ALBUM { get; set; }
        public int ANEXO { get; set; }
    
        public virtual OSSB_ALBUM OSSB_ALBUM { get; set; }
        public virtual ANEXO ANEXO1 { get; set; }
    }
}

Controllers/OssbImagemController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using ATIMO.ViewModel;
using ATIMO.Models;
using System.Web;
using System.IO;
using System.Threading.Tasks;
using ATIMO;
using System.Collections.Generic;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.pdf.draw;

namespace Atimo.Controllers
{

    public class OssbImagemController : FuncionarioController
    {
        private readonly ATIMOEntities _db = new ATIMOEntities();

        //
        // GET: /OssbServico/

        public ActionResult Index(int id = 0)
        {
            var viewModel = new OssbImagemViewModel()
            {
                Ossb = id,
                Items = _db
                .OSSB_ALBUM
                .Include(ab => ab.OSSB_IMAGEM)
                .Where(ab => ab.OSSB == id)
                 .ToArray()
            };

            return View(viewModel);
        }

        public async Task<FileResult> GetImagem(Int32 id)
        {
            var imagem = await _db.OSSB_IMAGEM
                 .Include(om => om.ANEXO1)
                 .FirstOrDefaultAsync(img => img.ID == id);

            if (imagem != null)
            {
                return File(imagem.ANEXO1.BUFFER, MimeMapping.GetMimeMapping(imagem.ANEXO1.NOME), imagem.ANEXO1.NOME);
            }
            else
                return null;
        }

        public async Task<JsonResult> PermutarImagens(Int32 a, Int32 b)
        {
            var imagemA = await _db.OSSB_IMAGEM
                 .FirstOrDefaultAsync(img => img.ID == a);

            var imagemB = await _db.OSSB_IMAGEM
                 .FirstOrDefaultAsync(img => img.ID == b);

            if (imagemA != null && imagemB != null)
            {
                var a_anexo = imagemA.ANEXO;
                var a_desc = imagemA.DESCRICAO;

                imagemA.ANEXO = imagemB.ANEXO;
                imagemA.DESCRICAO = imagemB.DESCRICAO;

                imagemB.ANEXO = a_anexo;
                imagemB.DESCRICAO = a_desc;

                await _db.SaveChangesAsync();

                return Json(new { status = 0 }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { status = 1}, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> UpdateAlbumDesc(Int32 id, string desc)
        {

                var album = await _db
                    .OSSB_ALBUM
                    .FirstOrDefaultAsync(ab => ab.ID == id);

                if (album == null)
                    return Json(new { status = 1 }, JsonRequestBehavior.AllowGet);

                album.DESCRICAO = desc;

                _db.Entry(album)
                    .State = EntityState.Modified;

                await _db.SaveChangesAsync();

                return Json(new { status = 0 }, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> UpdateImageDesc(Int32 id, string desc)
        {

                var imagem = await _db
                    .OSSB_IMAGEM
                    .FirstOrDefaultAsync(img => img.ID == id);

                if (imagem == null)
                    return Json(new { status = 1 }, JsonRequestBehavior.AllowGet);

                imagem.DESCRICAO = desc;

                _db.Entry(imagem)
                    .State = EntityState.Modified;

                await _db.SaveChangesAsync();

                return Json(new { status = 0 }, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> DeleteImage(Int32 id)
        {
                var image = await _db
                  .OSSB_IMAGEM
                   .Include(img => img.ANEXO1)
                    .FirstOrDefaultAsync(img => img.ID == id);

                if (image == null)
                    return Json(new { status = 1 }, JsonRequestBehavior.AllowGet);

                _db.Entry(image.ANEXO1)
                    .State = EntityState.Deleted;

                _db.Entry(image)
                    .State = EntityState.Deleted;

                await _db.SaveChangesAsync();

                return Json(new { status = 0 }, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> DeleteAlbum(Int32 id)
        {
                var album = await _db
                  .OSSB_ALBUM
                   .Include(ab => ab.OSSB_IMAGEM)
                   .Include(ab => ab.OSSB_IMAGEM.Select(img => img.ANEXO1))
                    .FirstOrDefaultAsync(ab => ab.ID == id);

                if (album == null)
                    return Json(new { status = 1 }, JsonRequestBehavior.AllowGet);

                foreach (var img in album.OSSB_IMAGEM)
                {
                    _db.Entry(img.ANEXO1)
                        .State = EntityState.Deleted;

                    _db.Entry(img)
                        .State = EntityState.Deleted;

                }

                _db.Entry(album)
                    .State = EntityState.Deleted;


                await _db.SaveChangesAsync();

                return Json(new { status = 0 }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> FileUpload(Int32 ossb, IEnumerable<HttpPostedFileBase> files)
        {
            if (files.Any())
            {
                var album = new OSSB_ALBUM()
                {
                    OSSB = ossb,
                    DESCRICAO = "",
                };

                foreach (var file in files)
                {
                    if (file != null)
                    {
                        String filename = Path.GetFileName(file.FileName);

                        byte[] data = new byte[file.InputStream.Length];

                        await file.InputStream.ReadAsync(data, 0, (int)file.InputStream.Length);

                        album.OSSB_IMAGEM.Add(new OSSB_IMAGEM() { DESCRICAO = DateTime.Today.ToString("dd/MM/yyyy") + " - ", ANEXO1 = new ANEXO() { BUFFER = data, NOME = file.FileName } });
                    }
                }

                _db.OSSB_ALBUM.Add(album);

                await _db.SaveChangesAsync();


            }

            return Redirect(Request.UrlReferrer.ToString());
        }




        [HttpPost]
        public async Task<ActionResult> FileUploadAlbum(Int32 album, IEnumerable<HttpPostedFileBase> files)
        {
            if (files.Any())
            {
                foreach (var file in files)
                {
                    if (file != null)
                    {
                        String filename = Path.GetFileName(file.FileName);

                        byte[] data = new byte[file.InputStream.Length];

                        await file.InputStream.ReadAsync(data, 0, (int)file.InputStream.Length);

                        _db.OSSB_IMAGEM.Add(new OSSB_IMAGEM() { ALBUM = album, DESCRICAO = DateTime.Today.ToString("dd/MM/yyyy") + " - ", ANEXO1 = new ANEXO() { BUFFER = data, NOME = file.FileName } });
                    }
                }

                await _db.SaveChangesAsync();


            }

            return Redirect(Request.UrlReferrer.ToString());
        }


        sealed class PageEventHandler : PdfPageEventHelper
        {
            public Controller Controller;

            public PageEventHandler(Controller controller)
            {
                Controller = controller;
            }

            public override void OnEndPage(PdfWriter writer, Document document)
            {
                var cb = writer.DirectContent;

                Font normalFont = FontFactory.GetFont(FontFactory.TIMES, 9);

                Font boldFont = FontFactory.GetFont(FontFactory.TIMES_BOLD, 9);

                float y = document.PageSize.GetBottom(document.BottomMargin);

                cb.MoveTo(document.LeftMargin, y);

                cb.SetColorStroke(new BaseColor(98, 36, 35));

                cb.LineTo(document.PageSize.GetRight(document.RightMargin), y);

                cb.Stroke();

                String[] texts = new String[]
                {
                    "São Bento Engenharia | Tel. +55 11 3331-1897",
                    "Rua Ipojuca, 54 | CEP 03304-050 – São Paulo – SP",
                    "ATENDIMENTO@SAOBENTOSERVICOS.COM.BR",
                    "WWW.SAOBENTOSERVICOS.COM.BR"
                };

                Font[] fonts = new Font[]
                {
                    boldFont,normalFont,boldFont,boldFont
                };

                y -= 10;

                for (Int32 it = 0; it < 4; ++it)
                {
                    String text = texts[it];
                    Font font = fonts[it];

                    y -= 2;

                    cb.BeginText();

                    cb.SetFontAndSize(font.BaseFont, 9);

                    float x = document.LeftMargin + (document.PageSize.GetRight(document.RightMargin) - document.LeftMargin) / 2 - (font.BaseFont.GetWidthPoint(text, 9) / 2);

                    cb.SetTextMatrix(x, y);

                    cb.ShowText(text);

                    cb.EndText();

                    y -= font.Size;
                }

            }

        }

        public static IEnumerable<IEnumerable<T>> TakeChunks<T>(IEnumerable<T> source, int size)
        {

            var list = new List<T>(size);

            foreach (T item in source)
            {
                list.Add(item);

                if (list.Count == size)
                {
                    List<T> chunk = list;
                    list = new List<T>(size);
                    yield return chunk;
                }
            }

            if (list.Count > 0)
            {
                yield return list;
            }
        }

        public FileContentResult GetRelatorioPDF(int id = 0)
        {
            if (Session.IsFuncionario())
            {
                OSSB ossb = _db.OSSB
                    .Include(o => o.PESSOA)
                    .Include(o => o.PROJETO1)

Views/OssbImagem/Index.cshtml
@model ATIMO.ViewModel.OssbImagemViewModel

@{
    ViewBag.Title = "Átimo - OSSB Imagem";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("MenuOperacional")

<div class="main">
    <div class="container" ng-app="ImageGallery" ng-controller="ImageGalleryController">
        <div class="row">
            <div class="widget">
                <div class="widget-header">
                    <i class="fa fa-wrench"></i>
                    <h3>OSSB/IMAGENS</h3>
                </div>

                <div class="widget-content">
                    <div class="col-md-12">
                        <a class="btn btn-info" href="~/OssbImagem/GetRelatorioPDF/@Model.Ossb">
                            <i class="fa fa-file-pdf-o"></i>
                            Gerar Relatório
                        </a>
                        <hr />
                    </div>
                    <div class="col-md-12">
                        @using (Html.BeginForm("FileUpload", "OssbImagem", new { ossb = @Model.Ossb }, FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)


                            <input type="file" name="files" accept="image/*" multiple="multiple" data-fancybox-type="iframe">
                            <input type="submit" value="Enviar" />
                        }
                    </div>
                </div>
            </div>
        </div>

        <div class="row" ng-repeat="album in albuns">
            <div class="widget">
                <div class="widget-header">
                    <i class="fa fa-photo"></i>
                    <h3>{{getLetter($index)}}</h3>
                </div>


                <div class="widget-content" style="position: relative;">
                    <div class="col-md-12 thumbnail" style="display: flex;flex-wrap:wrap">
                        <div style="margin: auto; overflow: hidden;" ng-drop="true" ng-drag="true" ng-drop-success="onDropComplete($index, album, $data, $event)" ng-drag-data="{album: album, image: image}" ng-repeat="image in album.images">
                            <div class="thumbnail">
                                <div class="caption" style="max-width: 300px; overflow: hidden;">
                                    <span style="font-weight:bold">{{($index + 1) + getLetter($parent.$index)}}</span>

                                    <button type="button" class="close pull-right" aria-label="Close" ng-click="deletar(album, image)">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>

                                <img ng-src="~/OssbImagem/GetImagem/{{image.id}}" alt="Lights" style="width: 300px; height: 300px;display:block; transition: transform .2s ease-in-out;">

                                <div class="caption" style="height: 150px; max-width: 300px; overflow: hidden;">
                                    <textarea ng-mousedown="$event.stopPropagation();" class="uppercase" rows="5" maxlength="150" style="overflow: hidden; border-style: none; border-color: transparent; width: 100%; height: 100%;" ng-change="salvarImagem(image);" ng-model="image.desc"></textarea>
                                </div>
                            </div>
                        </div>

                        <div style="margin: auto; overflow: hidden;">
                            <div class="thumbnail">
                                <form style="width: 300px; height: 489px" action="{{'/OssbImagem/FileUploadAlbum/?album=' + album.id}}" enctype="multipart/form-data" method="post">
                                    <input type="file" name="files" accept="image/*" multiple="multiple" data-fancybox-type="iframe">
                                    <input type="submit" value="Enviar" />
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12" style="margin: auto; overflow: hidden;">
                        <div style="text-align: center;">
                            CONCLUSÃO
                        </div>

                        <div>
                            <textarea class="uppercase" rows="1" maxlength="1024" style="overflow: hidden; border-style: none; border-color: transparent; width: 100%; height: 100%;" ng-change="salvarAlbum(album);" ng-model="album.desc"></textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@Html.Partial("Rodape")

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/ngDraggable.js"></script>

    <style>
        [ng-drag] {
            position: relative;
        }

        [ng-drop] {
            position: relative;
        }

        [ng-drag].drag-over {
            border: solid 1px red;
        }

        [ng-drag].dragging {
            opacity: 0.5;
        }

        [ng-drop].drag-enter {
            border: solid 1px red;
        }
    </style>

    <script>
        var app = angular.module("ImageGallery", ['ngDraggable']);

        app.controller("ImageGalleryController", function ($scope, $http) {
            $scope.albuns = [
              @Html.Raw(@String.Join(", ",
                Model.Items.Select(ab => "{id: " +ab.ID +", desc: '"+ ab.DESCRICAO + "', images: [" + String.Join(", ", ab.OSSB_IMAGEM.Select(img => "{" + "id: " +img.ID +  ", updated: false,  desc: "+ (img.DESCRICAO ==null? "null" : ("'" +@HttpUtility.JavaScriptStringEncode(img.DESCRICAO )+"'")) + "}")) + "]}")))
            ];

            $scope.onDropComplete = function (index, album, album_image, evt) {
                var otherObj = album.images[index];
                var otherIndex = album_image.album.images.indexOf(album_image.image);

                if (album_image.image != otherObj) {
                    $http({
                        url: "/OssbImagem/PermutarImagens/?a=" + album_image.image.id + '&b=' + otherObj.id,
                        method: "GET",
                    }).then(function (response) {
                        if (response.data.status == 0) {
                            album.images[index] = album_image.image;
                            album_image.album.images[otherIndex] = otherObj;
                        }
                    });
                }
            }

            $scope.getLetter = function (index) {
                return String.fromCharCode(65 + index);
            }

            var salvarImagemTimer;
            var salvarAlbumTimer;

            $scope.salvarImagem = function (image) {
                window.clearTimeout(salvarImagemTimer);

                salvarImagemTimer = window.setTimeout(function () {
                    $http({
                        url: "/OssbImagem/UpdateImageDesc/?id=" + image.id + "&desc=" + image.desc.toUpperCase(),
                        method: "GET",
                    }).then(function (response) {

                    });
                }, 300);

            };

            $scope.salvarAlbum = function (album) {
                window.clearTimeout(salvarAlbumTimer);

                salvarAlbumTimer = window.setTimeout(function () {

                    $http({
                        url: "/OssbImagem/UpdateAlbumDesc/?id=" + album.id + "&desc=" + album.desc.toUpperCase(),
                        method: "GET",
                    }).then(function (response) {

                    });
                } , 300);
            };

            $scope.textChanged = function (imagem) {
                imagem.updated = true;
            }

            $scope.deletar_album = function (album) {
                $http({
                    url: "/OssbImagem/DeleteAlbum/?id=" + album.id,
                    method: "GET",
                }).then(function (response) {
                    if (response.data.status == 0) {
                        $scope.albuns.splice($scope.albuns.indexOf(album), 1);
                    }
                });
            };

            $scope.deletar = function (album, image) {
                $http({
                    url: "/OssbImagem/DeleteImage/?id=" + image.id,
                    method: "GET",
                }).then(function (response) {
                    if (response.data.status == 0) {
                        album.images.splice(album.images.indexOf(image), 1);

                        if (album.images.length == 0) {
                            $scope.albuns.splice($scope.albuns.indexOf(album), 1);
                        }
                    }
                });
            };
        });
    </script>
}